import {
  createDocumentRoot,
  figureBlock,
  mentionInline,
  type NoteDocument,
  seedGeneratedBlockIds,
  textInline,
} from "./noteDocument";

export const initialNoteDocument: NoteDocument = {
  schemaVersion: 1,
  id: "note-1",
  title: "Rich note",
  tags: ["json-document", "rich"],
  root: createDocumentRoot([
    {
      id: "block-1",
      kind: "element",
      type: "paragraph",
      flow: "block",
      children: [
        textInline("Plain "),
        textInline("bold", [{ type: "bold" }]),
        textInline(" "),
        textInline("italic", [{ type: "italic" }]),
        textInline(" "),
        textInline("code", [{ type: "code" }]),
        textInline(" "),
        textInline("link", [{ type: "link", href: "https://example.com" }]),
        textInline(" "),
        mentionInline("user-ada", "Ada"),
      ],
    },
    figureBlock("figure-1", "/sample-figure.svg", "Figure"),
    {
      id: "block-2",
      kind: "element",
      type: "paragraph",
      flow: "block",
      children: [textInline("After figure.")],
    },
    {
      id: "heading-1",
      kind: "element",
      type: "heading",
      flow: "block",
      attrs: { level: 2 },
      level: 2,
      children: [textInline("Outline")],
    },
    {
      id: "quote-1",
      kind: "element",
      type: "quote",
      flow: "block",
      children: [textInline("Quote block")],
    },
    {
      id: "list-1",
      kind: "element",
      type: "listItem",
      flow: "block",
      attrs: { ordered: false, depth: 0 },
      ordered: false,
      depth: 0,
      children: [textInline("List item")],
    },
    {
      id: "code-1",
      kind: "element",
      type: "codeBlock",
      flow: "block",
      attrs: { language: "ts" },
      language: "ts",
      text: "const value = 1;",
      children: [textInline("const value = 1;")],
    },
  ]),
};

seedGeneratedBlockIds(initialNoteDocument.root.children);
